set(EPICS_BASE_ROOT "${CMAKE_SOURCE_DIR}/epics-base")
set(EPICS_BASE_INCLUDE_DIRS "${EPICS_BASE_ROOT}/include")

add_library(Com STATIC IMPORTED)
target_include_directories(Com INTERFACE "${EPICS_BASE_INCLUDE_DIRS}")
set_target_properties(Com PROPERTIES IMPORTED_LOCATION "${EPICS_BASE_ROOT}/lib/$ENV{EPICS_HOST_ARCH}/${CMAKE_STATIC_LIBRARY_PREFIX}Com${CMAKE_STATIC_LIBRARY_SUFFIX}")
if(WIN32)
  target_include_directories(Com INTERFACE "${EPICS_BASE_INCLUDE_DIRS}/os/win32")
else()
  target_include_directories(Com INTERFACE "${EPICS_BASE_INCLUDE_DIRS}/os/Linux")
endif()
if(MSVC)
  target_include_directories(Com INTERFACE "${EPICS_BASE_INCLUDE_DIRS}/compiler/msvc")
else()
  target_include_directories(Com INTERFACE "${EPICS_BASE_INCLUDE_DIRS}/compiler/gcc")
endif()
